// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class ApiIngest
{
    [Key]
    public long IngestId { get; set; }

    [StringLength(200)]
    public string Source { get; set; }

    public long? ExternalId { get; set; }

    public string Payload { get; set; }

    public DateTime? DateCreated { get; set; }
}