// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

[Index("Name", Name = "UQ__BettingM__737584F64294A9B6", IsUnique = true)]
public partial class BettingMarkets
{
    [Key]
    public int Id { get; set; }

    [StringLength(150)]
    public string Name { get; set; }

    [InverseProperty("Market")]
    public virtual ICollection<BettingOutcomes> BettingOutcomes { get; set; } = new List<BettingOutcomes>();

    [InverseProperty("Market")]
    public virtual ICollection<Odds> Odds { get; set; } = new List<Odds>();
}