// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class BettingOutcomes
{
    [Key]
    public int Id { get; set; }

    public int? MarketId { get; set; }

    [StringLength(150)]
    public string Name { get; set; }

    [ForeignKey("MarketId")]
    [InverseProperty("BettingOutcomes")]
    public virtual BettingMarkets Market { get; set; }

    [InverseProperty("Outcome")]
    public virtual ICollection<Odds> Odds { get; set; } = new List<Odds>();
}