// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Coaches
{
    [Key]
    public long CoachId { get; set; }

    public long? TeamId { get; set; }

    [StringLength(300)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Nationality { get; set; }

    public long? ExternalId { get; set; }

    public DateTime? DateCreated { get; set; }

    [ForeignKey("TeamId")]
    [InverseProperty("Coaches")]
    public virtual Teams Team { get; set; }
}