// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Countries
{
    [Key]
    public int Id { get; set; }

    [StringLength(200)]
    public string Name { get; set; }

    [StringLength(10)]
    public string Iso2 { get; set; }

    public DateTime? DateCreated { get; set; }

    [InverseProperty("Country")]
    public virtual ICollection<Leagues> Leagues { get; set; } = new List<Leagues>();

    [InverseProperty("Country")]
    public virtual ICollection<Teams> Teams { get; set; } = new List<Teams>();

    [InverseProperty("Country")]
    public virtual ICollection<Venues> Venues { get; set; } = new List<Venues>();
}