// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

[Index("Code", Name = "UQ__EventTyp__A25C5AA77C543CEF", IsUnique = true)]
public partial class EventTypes
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Desc { get; set; }

    [InverseProperty("EventType")]
    public virtual ICollection<FixtureEvents> FixtureEvents { get; set; } = new List<FixtureEvents>();
}