// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

[Index("Code", Name = "UQ__FixtureS__A25C5AA7D11445AA", IsUnique = true)]
public partial class FixtureStatuses
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Desc { get; set; }

    [InverseProperty("FixtureStatus")]
    public virtual ICollection<Fixtures> Fixtures { get; set; } = new List<Fixtures>();
}