// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Fixtures
{
    [Key]
    public long FixtureId { get; set; }

    public long? LeagueId { get; set; }

    public int? SeasonId { get; set; }

    public long? VenueId { get; set; }

    public long? HomeTeamId { get; set; }

    public long? AwayTeamId { get; set; }

    public DateTime? Kickoff { get; set; }

    public int? FixtureStatusId { get; set; }

    public int? ScoreHome { get; set; }

    public int? ScoreAway { get; set; }

    public long? ExternalId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? DateCreated { get; set; }

    public int ApiFixtureId { get; set; }

    [ForeignKey("AwayTeamId")]
    [InverseProperty("FixturesAwayTeam")]
    public virtual Teams AwayTeam { get; set; }

    [InverseProperty("Fixture")]
    public virtual ICollection<FixtureEvents> FixtureEvents { get; set; } = new List<FixtureEvents>();

    [ForeignKey("FixtureStatusId")]
    [InverseProperty("Fixtures")]
    public virtual FixtureStatuses FixtureStatus { get; set; }

    [ForeignKey("HomeTeamId")]
    [InverseProperty("FixturesHomeTeam")]
    public virtual Teams HomeTeam { get; set; }

    [ForeignKey("LeagueId")]
    [InverseProperty("Fixtures")]
    public virtual Leagues League { get; set; }

    [InverseProperty("Fixture")]
    public virtual ICollection<Lineups> Lineups { get; set; } = new List<Lineups>();

    [InverseProperty("Fixture")]
    public virtual ICollection<Odds> Odds { get; set; } = new List<Odds>();

    [InverseProperty("Fixture")]
    public virtual ICollection<Predictions> Predictions { get; set; } = new List<Predictions>();

    [ForeignKey("SeasonId")]
    [InverseProperty("Fixtures")]
    public virtual Seasons Season { get; set; }

    [InverseProperty("Fixture")]
    public virtual ICollection<Statisticals> Statisticals { get; set; } = new List<Statisticals>();

    [ForeignKey("VenueId")]
    [InverseProperty("Fixtures")]
    public virtual Venues Venue { get; set; }
}