// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class FixtureEvents
{
    [Key]
    public long EventId { get; set; }

    public long? FixtureId { get; set; }

    public long? TeamId { get; set; }

    public long? PlayerId { get; set; }

    public int? EventTypeId { get; set; }

    public int? Minute { get; set; }

    [StringLength(1000)]
    public string ExtraInfo { get; set; }

    public DateTime? DateCreated { get; set; }

    [ForeignKey("EventTypeId")]
    [InverseProperty("FixtureEvents")]
    public virtual EventTypes EventType { get; set; }

    [ForeignKey("FixtureId")]
    [InverseProperty("FixtureEvents")]
    public virtual Fixtures Fixture { get; set; }

    [ForeignKey("PlayerId")]
    [InverseProperty("FixtureEvents")]
    public virtual Players Player { get; set; }

    [ForeignKey("TeamId")]
    [InverseProperty("FixtureEvents")]
    public virtual Teams Team { get; set; }
}