// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Leagues
{
    [Key]
    public long LeagueId { get; set; }

    [StringLength(300)]
    public string Name { get; set; }

    public int? CountryId { get; set; }

    [StringLength(50)]
    public string Season { get; set; }

    public long? ExternalId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? DateCreated { get; set; }

    [ForeignKey("CountryId")]
    [InverseProperty("Leagues")]
    public virtual Countries Country { get; set; }

    [InverseProperty("League")]
    public virtual ICollection<Fixtures> Fixtures { get; set; } = new List<Fixtures>();

    [InverseProperty("League")]
    public virtual ICollection<Seasons> Seasons { get; set; } = new List<Seasons>();

    [InverseProperty("League")]
    public virtual ICollection<Standings> Standings { get; set; } = new List<Standings>();
}