// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Lineups
{
    [Key]
    public long LineupId { get; set; }

    public long? FixtureId { get; set; }

    public long? TeamId { get; set; }

    public long? PlayerId { get; set; }

    public bool? IsStarter { get; set; }

    public int? PositionId { get; set; }

    public DateTime? DateCreated { get; set; }

    [ForeignKey("FixtureId")]
    [InverseProperty("Lineups")]
    public virtual Fixtures Fixture { get; set; }

    [ForeignKey("PlayerId")]
    [InverseProperty("Lineups")]
    public virtual Players Player { get; set; }

    [ForeignKey("PositionId")]
    [InverseProperty("Lineups")]
    public virtual PlayerPositions Position { get; set; }

    [ForeignKey("TeamId")]
    [InverseProperty("Lineups")]
    public virtual Teams Team { get; set; }
}