// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Odds
{
    [Key]
    public long OddsId { get; set; }

    public long? FixtureId { get; set; }

    public int? ProviderId { get; set; }

    public int? MarketId { get; set; }

    public int? OutcomeId { get; set; }

    [Column(TypeName = "decimal(12, 4)")]
    public decimal? Value { get; set; }

    public DateTime? RetrievedAt { get; set; }

    [ForeignKey("FixtureId")]
    [InverseProperty("Odds")]
    public virtual Fixtures Fixture { get; set; }

    [ForeignKey("MarketId")]
    [InverseProperty("Odds")]
    public virtual BettingMarkets Market { get; set; }

    [ForeignKey("OutcomeId")]
    [InverseProperty("Odds")]
    public virtual BettingOutcomes Outcome { get; set; }

    [ForeignKey("ProviderId")]
    [InverseProperty("Odds")]
    public virtual PaymentProviders Provider { get; set; }
}