// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class PasswordResets
{
    [Key]
    public Guid ResetId { get; set; }

    public Guid? UserId { get; set; }

    [StringLength(128)]
    public string Token { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public bool? Used { get; set; }

    public DateTime? DateCreated { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("PasswordResets")]
    public virtual Users User { get; set; }
}