// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

[Index("Code", Name = "UQ__PaymentS__A25C5AA7AAFFE9C3", IsUnique = true)]
public partial class PaymentStatuses
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Desc { get; set; }

    [InverseProperty("PaymentStatus")]
    public virtual ICollection<Payments> Payments { get; set; } = new List<Payments>();
}