// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

[Index("Slug", Name = "UQ__PaymentP__BC7B5FB632667CB2", IsUnique = true)]
public partial class PaymentProviders
{
    [Key]
    public int ProviderId { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Slug { get; set; }

    public string Config { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? DateCreated { get; set; }

    [InverseProperty("Provider")]
    public virtual ICollection<Odds> Odds { get; set; } = new List<Odds>();

    [InverseProperty("Provider")]
    public virtual ICollection<Payments> Payments { get; set; } = new List<Payments>();

    [InverseProperty("Provider")]
    public virtual ICollection<ProviderWebhookEvents> ProviderWebhookEvents { get; set; } = new List<ProviderWebhookEvents>();
}