// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Payments
{
    [Key]
    public long PaymentId { get; set; }

    public Guid? UserId { get; set; }

    public int? ProviderId { get; set; }

    [StringLength(200)]
    public string ProviderTransactionId { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? Amount { get; set; }

    [StringLength(8)]
    public string Currency { get; set; }

    public int? PaymentStatusId { get; set; }

    public string Metadata { get; set; }

    public bool? IsCompleted { get; set; }

    public DateTime? DateCreated { get; set; }

    [ForeignKey("PaymentStatusId")]
    [InverseProperty("Payments")]
    public virtual PaymentStatuses PaymentStatus { get; set; }

    [ForeignKey("ProviderId")]
    [InverseProperty("Payments")]
    public virtual PaymentProviders Provider { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Payments")]
    public virtual Users User { get; set; }
}