// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class PlayerTransfers
{
    [Key]
    public long TransferId { get; set; }

    public long? PlayerId { get; set; }

    public long? FromTeamId { get; set; }

    public long? ToTeamId { get; set; }

    public DateTime? TransferDate { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? Fee { get; set; }

    public long? ExternalId { get; set; }

    public DateTime? DateCreated { get; set; }

    [ForeignKey("FromTeamId")]
    [InverseProperty("PlayerTransfersFromTeam")]
    public virtual Teams FromTeam { get; set; }

    [ForeignKey("PlayerId")]
    [InverseProperty("PlayerTransfers")]
    public virtual Players Player { get; set; }

    [ForeignKey("ToTeamId")]
    [InverseProperty("PlayerTransfersToTeam")]
    public virtual Teams ToTeam { get; set; }
}