// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

[Index("Code", Name = "UQ__PlayerPo__A25C5AA70B865EDE", IsUnique = true)]
public partial class PlayerPositions
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Desc { get; set; }

    [InverseProperty("Position")]
    public virtual ICollection<Lineups> Lineups { get; set; } = new List<Lineups>();

    [InverseProperty("Position")]
    public virtual ICollection<Players> Players { get; set; } = new List<Players>();
}