// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Players
{
    [Key]
    public long PlayerId { get; set; }

    public long? TeamId { get; set; }

    [StringLength(150)]
    public string FirstName { get; set; }

    [StringLength(150)]
    public string LastName { get; set; }

    [StringLength(200)]
    public string CommonName { get; set; }

    public int? PositionId { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    [StringLength(100)]
    public string Nationality { get; set; }

    public long? ExternalId { get; set; }

    public int? ShirtNumber { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? DateCreated { get; set; }

    [InverseProperty("Player")]
    public virtual ICollection<FixtureEvents> FixtureEvents { get; set; } = new List<FixtureEvents>();

    [InverseProperty("Player")]
    public virtual ICollection<Lineups> Lineups { get; set; } = new List<Lineups>();

    [InverseProperty("Player")]
    public virtual ICollection<PlayerTransfers> PlayerTransfers { get; set; } = new List<PlayerTransfers>();

    [ForeignKey("PositionId")]
    [InverseProperty("Players")]
    public virtual PlayerPositions Position { get; set; }

    [InverseProperty("Player")]
    public virtual ICollection<Statisticals> Statisticals { get; set; } = new List<Statisticals>();

    [ForeignKey("TeamId")]
    [InverseProperty("Players")]
    public virtual Teams Team { get; set; }
}