// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class ProviderWebhookEvents
{
    [Key]
    public long EventId { get; set; }

    public int? ProviderId { get; set; }

    [StringLength(200)]
    public string EventType { get; set; }

    public string Payload { get; set; }

    public DateTime? ReceivedAt { get; set; }

    public bool? Processed { get; set; }

    [ForeignKey("ProviderId")]
    [InverseProperty("ProviderWebhookEvents")]
    public virtual PaymentProviders Provider { get; set; }
}