// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Seasons
{
    [Key]
    public int SeasonId { get; set; }

    public long? LeagueId { get; set; }

    [StringLength(20)]
    public string Year { get; set; }

    public long? ExternalId { get; set; }

    public DateTime? DateCreated { get; set; }

    [InverseProperty("Season")]
    public virtual ICollection<Fixtures> Fixtures { get; set; } = new List<Fixtures>();

    [ForeignKey("LeagueId")]
    [InverseProperty("Seasons")]
    public virtual Leagues League { get; set; }

    [InverseProperty("Season")]
    public virtual ICollection<Standings> Standings { get; set; } = new List<Standings>();
}