// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Sessions
{
    [Key]
    public Guid SessionId { get; set; }

    public Guid? UserId { get; set; }

    public string JwtToken { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public bool? IsRevoked { get; set; }

    public DateTime? DateCreated { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Sessions")]
    public virtual Users User { get; set; }
}