// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Standings
{
    [Key]
    public long StandingId { get; set; }

    public long? LeagueId { get; set; }

    public int? SeasonId { get; set; }

    public long? TeamId { get; set; }

    public int? Rank { get; set; }

    public int? Played { get; set; }

    public int? Won { get; set; }

    public int? Draw { get; set; }

    public int? Lost { get; set; }

    public int? GoalsFor { get; set; }

    public int? GoalsAgainst { get; set; }

    public int? Points { get; set; }

    public DateTime? DateCreated { get; set; }

    [ForeignKey("LeagueId")]
    [InverseProperty("Standings")]
    public virtual Leagues League { get; set; }

    [ForeignKey("SeasonId")]
    [InverseProperty("Standings")]
    public virtual Seasons Season { get; set; }

    [ForeignKey("TeamId")]
    [InverseProperty("Standings")]
    public virtual Teams Team { get; set; }
}