// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Statisticals
{
    [Key]
    public long StatId { get; set; }

    public long? FixtureId { get; set; }

    public long? TeamId { get; set; }

    public long? PlayerId { get; set; }

    [StringLength(200)]
    public string KeyName { get; set; }

    [StringLength(200)]
    public string Value { get; set; }

    public DateTime? DateCreated { get; set; }

    [ForeignKey("FixtureId")]
    [InverseProperty("Statisticals")]
    public virtual Fixtures Fixture { get; set; }

    [ForeignKey("PlayerId")]
    [InverseProperty("Statisticals")]
    public virtual Players Player { get; set; }

    [ForeignKey("TeamId")]
    [InverseProperty("Statisticals")]
    public virtual Teams Team { get; set; }
}