// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Subscriptions
{
    [Key]
    public long SubscriptionId { get; set; }

    public Guid? UserId { get; set; }

    public int? TierId { get; set; }

    [StringLength(200)]
    public string ProviderSubscriptionId { get; set; }

    public int? SubscriptionStatusId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool? IsPaid { get; set; }

    public bool? AutoRenew { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateUpdated { get; set; }

    [ForeignKey("SubscriptionStatusId")]
    [InverseProperty("Subscriptions")]
    public virtual SubscriptionStatuses SubscriptionStatus { get; set; }

    [ForeignKey("TierId")]
    [InverseProperty("Subscriptions")]
    public virtual SubscriptionTiers Tier { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Subscriptions")]
    public virtual Users User { get; set; }
}