// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

[Index("Code", Name = "UQ__Subscrip__A25C5AA7FA5E517A", IsUnique = true)]
public partial class SubscriptionStatuses
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Desc { get; set; }

    [InverseProperty("SubscriptionStatus")]
    public virtual ICollection<Subscriptions> Subscriptions { get; set; } = new List<Subscriptions>();
}