// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class SubscriptionTiers
{
    [Key]
    public int TierId { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    [StringLength(20)]
    public string BillingInterval { get; set; }

    public string Features { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? DateCreated { get; set; }

    [InverseProperty("Tier")]
    public virtual ICollection<Subscriptions> Subscriptions { get; set; } = new List<Subscriptions>();
}