// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Teams
{
    [Key]
    public long TeamId { get; set; }

    [StringLength(300)]
    public string Name { get; set; }

    [StringLength(100)]
    public string ShortName { get; set; }

    public int? CountryId { get; set; }

    public int? Founded { get; set; }

    public long? ExternalId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? DateCreated { get; set; }

    [InverseProperty("Team")]
    public virtual ICollection<Coaches> Coaches { get; set; } = new List<Coaches>();

    [ForeignKey("CountryId")]
    [InverseProperty("Teams")]
    public virtual Countries Country { get; set; }

    [InverseProperty("Team")]
    public virtual ICollection<FixtureEvents> FixtureEvents { get; set; } = new List<FixtureEvents>();

    [InverseProperty("AwayTeam")]
    public virtual ICollection<Fixtures> FixturesAwayTeam { get; set; } = new List<Fixtures>();

    [InverseProperty("HomeTeam")]
    public virtual ICollection<Fixtures> FixturesHomeTeam { get; set; } = new List<Fixtures>();

    [InverseProperty("Team")]
    public virtual ICollection<Lineups> Lineups { get; set; } = new List<Lineups>();

    [InverseProperty("FromTeam")]
    public virtual ICollection<PlayerTransfers> PlayerTransfersFromTeam { get; set; } = new List<PlayerTransfers>();

    [InverseProperty("ToTeam")]
    public virtual ICollection<PlayerTransfers> PlayerTransfersToTeam { get; set; } = new List<PlayerTransfers>();

    [InverseProperty("Team")]
    public virtual ICollection<Players> Players { get; set; } = new List<Players>();

    [InverseProperty("Team")]
    public virtual ICollection<Standings> Standings { get; set; } = new List<Standings>();

    [InverseProperty("Team")]
    public virtual ICollection<Statisticals> Statisticals { get; set; } = new List<Statisticals>();
}