// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

[Index("Email", Name = "UQ__Users__A9D10534BC78EA17", IsUnique = true)]
public partial class Users
{
    [Key]
    public Guid UserId { get; set; }

    [StringLength(256)]
    public string Email { get; set; }

    [StringLength(32)]
    public string Phone { get; set; }

    [StringLength(512)]
    public string PasswordHash { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateUpdated { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? UpdatedBy { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<PasswordResets> PasswordResets { get; set; } = new List<PasswordResets>();

    [InverseProperty("User")]
    public virtual ICollection<Payments> Payments { get; set; } = new List<Payments>();

    [InverseProperty("User")]
    public virtual ICollection<Sessions> Sessions { get; set; } = new List<Sessions>();

    [InverseProperty("User")]
    public virtual ICollection<Subscriptions> Subscriptions { get; set; } = new List<Subscriptions>();
}