// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ORApp.Data.Models;

public partial class Venues
{
    [Key]
    public long VenueId { get; set; }

    [StringLength(300)]
    public string Name { get; set; }

    [StringLength(200)]
    public string City { get; set; }

    public int? CountryId { get; set; }

    public int? Capacity { get; set; }

    public long? ExternalId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? DateCreated { get; set; }

    [ForeignKey("CountryId")]
    [InverseProperty("Venues")]
    public virtual Countries Country { get; set; }

    [InverseProperty("Venue")]
    public virtual ICollection<Fixtures> Fixtures { get; set; } = new List<Fixtures>();
}